/** 获取我的习题册 */
export const REMEMBER_WORKBOOK_GET = 'REMEMBER_WORKBOOK_GET'
/** 清除我的习题册 */
export const REMEMBER_WORKBOOK_CLEAR = 'REMEMBER_WORKBOOK_CLEAR'
/** 增加习题册 */
export const REMEMBER_WORKBOOK_ADD = 'REMEMBER_WORKBOOK_ADD'
/** 获取全部习题册 */
export const REMEMBER_WORKBOOK_ALL = 'REMEMBER_WORKBOOK_ALL'
/** 清除全部习题册信息 */
export const REMEMBER_WORKBOOK_ALL_CLEAR = 'REMEMBER_WORKBOOK_ALL_CLEAR'
/** 获取习题册切换科目 */
export const REMEMBER_SUBJECT_CHANGE = 'REMEMBER_SUBJECT_CHANGE'
/** 获取习题册章节 */
export const REMEMBER_CHAPTER_GET = 'REMEMBER_CHAPTER_GET'
/** 清除章节数据 */
export const REMEMBER_CHAPTER_CLEAR = 'REMEMBER_CHAPTER_CLEAR'
/** 设置章节高度 */
export const REMEMBER_CHAPTER_SCROLL = 'REMEMBER_CHAPTER_SCROLL'
/** 获取章节练习题 */
export const REMEMBER_EXERCISE= 'REMEMBER_EXERCISE'
/** 章节练习题更改答案 */
export const REMEMBER_EXERCISE_CHANGE= 'REMEMBER_EXERCISE_CHANGE'
/** 提交章节练习题 */
export const REMEMBER_EXERCISE_POST= 'REMEMBER_EXERCISE_POST'
/** 清空章节练习题 */
export const REMEMBER_EXERCISE_CLEAR = 'REMEMBER_EXERCISE_CLEAR'
/** 设置练习题高度 */
export const REMEMBER_EXERCISE_SCROLL = 'REMEMBER_EXERCISE_SCROLL'
/** 例题查看 */
export const REMEMBER_EXAMPLE= 'REMEMBER_EXAMPLE'
/** 清空例题 */
export const REMEMBER_EXAMPLE_CLEAR = 'REMEMBER_EXAMPLE_CLEAR'
/** 例题收藏 */
export const REMEMBER_EXAMPLE_COLLECT_ADD = 'REMEMBER_EXAMPLE_COLLECT_ADD'
/** 例题取消 */
export const REMEMBER_EXAMPLE_COLLECT_REMOVE = 'REMEMBER_EXAMPLE_COLLECT_REMOVE'
