/** 获取我的习题册 */
export const REMEMBER_WORKBOOK_GET = 'REMEMBER_WORKBOOK_GET'
/** 获取习题册切换科目 */
export const REMEMBER_SUBJECT_CHANGE = 'REMEMBER_SUBJECT_CHANGE'
/** 获取习题册章节 */
export const REMEMBER_CHAPTER_GET = 'REMEMBER_CHAPTER_GET'
/** 清除章节数据 */
export const REMEMBER_CHAPTER_CLEAR = 'REMEMBER_CHAPTER_CLEAR'