/** 获取我的习题册 */
export const REMEMBER_WORKBOOK_GET = 'REMEMBER_WORKBOOK_GET'
/** 清除我的习题册 */
export const REMEMBER_WORKBOOK_CLEAR = 'REMEMBER_WORKBOOK_CLEAR'
/** 增加习题册 */
export const REMEMBER_WORKBOOK_ADD = 'REMEMBER_WORKBOOK_ADD'
/** 获取全部习题册 */
export const REMEMBER_WORKBOOK_ALL = 'REMEMBER_WORKBOOK_ALL'
/** 清除全部习题册信息 */
export const REMEMBER_WORKBOOK_ALL_CLEAR = 'REMEMBER_WORKBOOK_ALL_CLEAR'
/** 获取习题册切换科目 */
export const REMEMBER_SUBJECT_CHANGE = 'REMEMBER_SUBJECT_CHANGE'
/** 获取习题册章节 */
export const REMEMBER_CHAPTER_GET = 'REMEMBER_CHAPTER_GET'
/** 清除章节数据 */
export const REMEMBER_CHAPTER_CLEAR = 'REMEMBER_CHAPTER_CLEAR'
/** 获取章节练习题 */
export const REMEMBER_EXERCISE= 'REMEMBER_EXERCISE'
/** 提交章节练习题 */
export const REMEMBER_EXERCISE_POST= 'REMEMBER_EXERCISE_POST'
/** 清空章节练习题 */
export const REMEMBER_EXERCISE_CLEAR = 'REMEMBER_EXERCISE_CLEAR'
/** 例题查看 */
export const REMEMBER_EXEMPLE= 'REMEMBER_EXEMPLE'
/** 清空例题 */
export const REMEMBER_EXEMPLE_CLEAR = 'REMEMBER_EXEMPLE_CLEAR'
