/** 获取详细成绩报告单数据*/
export const GET_REPORT_DETAIL_SUCCESS = 'GET_REPORT_DETAIL_SUCCESS'
/**下拉框展现*/
export const CHAPTER_STATE_CHANGE = 'CHAPTER_STATE_CHANGE'
/**滚动条高度*/
export const REPORT_SCOLLER_HEIGHT = 'REPORT_SCOLLER_HEIGHT'
/** 获取教材章节*/
export const GET_REPORT_CHAPTER_SUCCESS = 'GET_REPORT_CHAPTER_SUCCESS'
/** 更换科目*/
export const REPORT_CHANGE_SUBJECT = 'REPORT_CHANGE_SUBJECT'