/** 获取班级习题册 */
export const WORKBOOK_STU = 'WORKBOOK_STU'
/** 清除班级习题册 */
export const WORKBOOK_STU_CLEAR = 'WORKBOOK_STU_CLEAR'
/** 获取习题册切换科目 */
export const WORKBOOK_STU_SUBJECT_CHANGE = 'WORKBOOK_STU_SUBJECT_CHANGE'

/** 获取习题册章节 */
export const WORKBOOK_STU_CHAPTER = 'WORKBOOK_STU_CHAPTER'
/** 清除章节数据 */
export const WORKBOOK_STU_CHAPTER_CLEAR = 'WORKBOOK_STU_CHAPTER_CLEAR'
/** 设置章节高度 */
export const WORKBOOK_STU_CHAPTER_SCROLL = 'WORKBOOK_STU_CHAPTER_SCROLL'
/** 获取练习题 */
export const WORKBOOK_STU_EXERCISE= 'WORKBOOK_STU_EXERCISE'
/** 练习题更改答案 */
export const WORKBOOK_STU_EXERCISE_CHANGE= 'WORKBOOK_STU_EXERCISE_CHANGE'
/** 提交练习题 */
export const WORKBOOK_STU_EXERCISE_POST= 'WORKBOOK_STU_EXERCISE_POST'
/** 清空练习题 */
export const WORKBOOK_STU_EXERCISE_CLEAR = 'WORKBOOK_STU_EXERCISE_CLEAR'
/** 设置练习题高度 */
export const WORKBOOK_STU_EXERCISE_SCROLL = 'WORKBOOK_STU_EXERCISE_SCROLL'