/*获取拍照历史ID*/
export const GET_CAMERA_HISTORYIDS_SUCCESS = 'GET_CAMERA_HISTORYIDS_SUCCESS'
/*获取拍照历史的题目*/
export const GET_CAMERA_HISTORYLIST_SUCCESS = 'GET_CAMERA_HISTORYLIST_SUCCESS'
/**切换学科 */
export const CAMERA_CHANGE_SUBJECT  = 'CAMERA_CHANGE_SUBJECT'
/*移除拍照历史的题目*/
export const DEL_CAMERA_HISTORYID_SUCCESS = 'DEL_CAMERA_HISTORYID_SUCCESS'
export const CAMERA_SCOLLER_HEIGHT = 'CAMERA_SCOLLER_HEIGHT'
export const CLEAR_CAMERA_HISTORY = 'CLEAR_CAMERA_HISTORY'
/*获取搜提结果IDS*/
export const GET_CAMERA_RESULTIDS_SUCCESS = 'GET_CAMERA_RESULTIDS_SUCCESS'
export const GET_CAMERA_RESULTIDS_ERROR = 'GET_CAMERA_RESULTIDS_ERROR'
/*获取搜提结果LIST*/
export const GET_CAMERA_RESULTLIST_SUCCESS = 'GET_CAMERA_RESULTLIST_SUCCESS'
export const GET_CAMERA_RESULTLIST_ERROR = 'GET_CAMERA_RESULTLIST_ERROR'
/*获取拍错题对应例题ID*/
export const GET_CAMERA_HISTORYEXAMPLEID_SUCCESS = 'GET_CAMERA_HISTORYEXAMPLEID_SUCCESS'
export const GET_CAMERA_HISTORYEXAMPLEID_ERROR = 'GET_CAMERA_HISTORYEXAMPLEID_ERROR'
/*提交人工搜索*/
export const POST_CAMERA_RESULTSEARCH_SUCCESS = 'POST_CAMERA_RESULTSEARCH_SUCCESS'
export const POST_CAMERA_RESULTSEARCH_ERROR = 'POST_CAMERA_RESULTSEARCH_ERROR'
/*设置例题*/
export const POST_CAMERA_EXAMPLE_SUCCESS = 'POST_CAMERA_EXAMPLE_SUCCESS'
export const POST_CAMERA_EXAMPLE_ERROR = 'POST_CAMERA_EXAMPLE_ERROR'
/*设置图片*/
export const SET_CAMERA_IMG = 'SET_CAMERA_IMG'
/*上传图片*/
export const POST_CAMERA_SUCCESS = 'POST_CAMERA_SUCCESS'
export const POST_CAMERA_ERROR = 'POST_CAMERA_ERROR'
