/*获取拍照历史ID*/
export const GET_CAMERA_HISTORYIDS_SUCCESS = 'GET_CAMERA_HISTORYIDS_SUCCESS'
export const GET_CAMERA_HISTORYIDS_ERROR = 'GET_CAMERA_HISTORYIDS_ERROR'
/*获取拍照历史的题目*/
export const GET_CAMERA_HISTORYLIST_SUCCESS = 'GET_CAMERA_HISTORYLIST_SUCCESS'
export const GET_CAMERA_HISTORYLIST_ERROR = 'GET_CAMERA_HISTORYLIST_ERROR'
/*移除拍照历史的题目*/
export const DEL_CAMERA_HISTORYID_SUCCESS = 'DEL_CAMERA_HISTORYID_SUCCESS'
export const DEL_CAMERA_HISTORYID_ERROR = 'DEL_CAMERA_HISTORYID_ERROR'
/*获取搜提结果IDS*/
export const GET_CAMERA_RESULTIDS_SUCCESS = 'GET_CAMERA_RESULTIDS_SUCCESS'
export const GET_CAMERA_RESULTIDS_ERROR = 'GET_CAMERA_RESULTIDS_ERROR'
/*获取搜提结果LIST*/
export const GET_CAMERA_RESULTLIST_SUCCESS = 'GET_CAMERA_RESULTLIST_SUCCESS'
export const GET_CAMERA_RESULTLIST_ERROR = 'GET_CAMERA_RESULTLIST_ERROR'
/*获取拍错题对应例题ID*/
export const GET_CAMERA_HISTORYEXAMPLEID_SUCCESS = 'GET_CAMERA_HISTORYEXAMPLEID_SUCCESS'
export const GET_CAMERA_HISTORYEXAMPLEID_ERROR = 'GET_CAMERA_HISTORYEXAMPLEID_ERROR'
/*提交人工搜索*/
export const POST_CAMERA_RESULTSEARCH_SUCCESS = 'POST_CAMERA_RESULTSEARCH_SUCCESS'
export const POST_CAMERA_RESULTSEARCH_ERROR = 'POST_CAMERA_RESULTSEARCH_ERROR'
/*设置例题*/
export const POST_CAMERA_EXAMPLE_SUCCESS = 'POST_CAMERA_EXAMPLE_SUCCESS'
export const POST_CAMERA_EXAMPLE_ERROR = 'POST_CAMERA_EXAMPLE_ERROR'
