/*获取拍照历史ID*/
export const GET_CAMERA_HISTORYIDS = 'GET_CAMERA_HISTORYIDS'
/*获取拍照历史的题目*/
export const GET_CAMERA_HISTORYLIST = 'GET_CAMERA_HISTORYLIST'
/**切换学科 */
export const CAMERA_CHANGE_SUBJECT  = 'CAMERA_CHANGE_SUBJECT'
/*移除拍照历史的题目*/
export const DEL_CAMERA_HISTORYID = 'DEL_CAMERA_HISTORYID'
export const CAMERA_SCOLLER_HEIGHT = 'CAMERA_SCOLLER_HEIGHT'
export const CLEAR_CAMERA_HISTORY = 'CLEAR_CAMERA_HISTORY'
/*获取搜提结果IDS*/
export const GET_CAMERA_RESULTIDS = 'GET_CAMERA_RESULTIDS'
/*获取搜提结果LIST*/
export const GET_CAMERA_RESULTLIST = 'GET_CAMERA_RESULTLIST'
/*获取拍错题对应例题ID*/
export const GET_CAMERA_HISTORYEXAMPLEID = 'GET_CAMERA_HISTORYEXAMPLEID'
/*提交人工搜索*/
export const POST_CAMERA_RESULTSEARCH = 'POST_CAMERA_RESULTSEARCH'
/*设置例题*/
export const POST_CAMERA_EXAMPLE = 'POST_CAMERA_EXAMPLE'
/*设置图片*/
export const SET_CAMERA_IMG = 'SET_CAMERA_IMG'
/*上传图片*/
export const POST_CAMERA = 'POST_CAMERA'
