/*短信注册账号*/
export const GET_REGISTER_MESSAGE_SUCCESS = 'GET_REGISTER_MESSAGE_SUCCESS'
export const GET_REGISTER_MESSAGE_ERROR = 'GET_REGISTER_MESSAGE_ERROR'
/*短信重置账号密码*/
export const GET_FORGET_MESSAGE_SUCCESS = 'GET_FORGET_MESSAGE_SUCCESS'
export const GET_FORGET_MESSAGE_ERROR = 'GET_FORGET_MESSAGE_ERROR'
/*登陆*/
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS'
export const GET_LOGIN_FAILED = 'GET_LOGIN_FAILED'
export const GET_LOGIN_ERROR = 'GET_LOGIN_ERROR'
/*设置密码*/
export const SET_PASSWORD_SUCCESS = 'SET_PASSWORD_SUCCESS'
export const SET_PASSWORD_ERROR = 'SET_PASSWORD_ERROR'
/*重置密码*/
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR'

export const SET_HEAD_IMG = 'SET_HEAD_IMG'
