/*获取首页数据*/
export const GET_STUDENT_INDEX_SUCCESS = 'GET_STUDENT_INDEX_SUCCESS'
export const GET_STUDENT_INDEX_ERROR = 'GET_STUDENT_INDEX_ERROR'

export const SET_HEAD_PHOTO = 'SET_HEAD_PHOTO'

/*获取首页数据*/
export const POST_STUDENT_INDEX_SUCCESS = 'POST_STUDENT_INDEX_SUCCESS'
export const POST_STUDENT_INDEX_ERROR = 'POST_STUDENT_INDEX_ERROR'