/** 获取归纳本列表ID*/
export const GET_ERROR_INDEXIDS = 'GET_ERROR_INDEXIDS'
export const GET_ERROR_INDEXLIST = 'GET_ERROR_INDEXLIST'
export const ERROR_SUBJECT_CHANGE = 'ERROR_SUBJECT_CHANGE'
export const ERROR_RELOAD = 'ERROR_RELOAD'
/** 获取归纳本更多习题ID*/
export const GET_ERROR_MOREIDS = 'GET_ERROR_MOREIDS'
export const GET_ERROR_MORELIST = 'GET_ERROR_MORELIST'
/** 获取归纳本拍错题列表ID*/
export const GET_ERROR_LISTIDS = 'GET_ERROR_LISTIDS'
export const GET_ERROR_LISTLIST = 'GET_ERROR_LISTLIST'
/** 获取归纳本推荐列表ID*/
export const GET_ERROR_RMDIDS = 'GET_ERROR_RMDIDS'
export const GET_ERROR_RMDLIST = 'GET_ERROR_RMDLIST'
/** 归纳本错题提交*/
export const POST_ERROR_RECOMMENDIDS = 'POST_ERROR_RECOMMENDIDS'
