/*获取归纳本列表ID*/
export const GET_ERROR_INDEXIDS_SUCCESS = 'GET_ERROR_INDEXIDS_SUCCESS'
export const GET_ERROR_INDEXIDS_ERROR = 'GET_ERROR_INDEXIDS_ERROR'
export const GET_ERROR_INDEXLIST_SUCCESS = 'GET_ERROR_INDEXLIST_SUCCESS'
export const GET_ERROR_INDEXLIST_ERROR = 'GET_ERROR_INDEXLIST_ERROR'
/*获取归纳本更多习题ID*/
export const GET_ERROR_MOREIDS_SUCCESS = 'GET_ERROR_MOREIDS_SUCCESS'
export const GET_ERROR_MOREIDS_ERROR = 'GET_ERROR_MOREIDS_ERROR'
export const GET_ERROR_MORELIST_SUCCESS = 'GET_ERROR_MORELIST_SUCCESS'
export const GET_ERROR_MORELIST_ERROR = 'GET_ERROR_MORELIST_ERROR'
/*获取归纳本错题列表ID*/
export const GET_ERROR_LISTIDS_SUCCESS = 'GET_ERROR_LISTIDS_SUCCESS'
export const GET_ERROR_LISTIDS_ERROR = 'GET_ERROR_LISTIDS_ERROR'
export const GET_ERROR_LISTLIST_SUCCESS = 'GET_ERROR_LISTLIST_SUCCESS'
export const GET_ERROR_LISTLIST_ERROR = 'GET_ERROR_LISTLIST_ERROR'
/*获取归纳本推荐列表ID*/
export const GET_ERROR_RMDIDS_SUCCESS = 'GET_ERROR_RMDIDS_SUCCESS'
export const GET_ERROR_RMDIDS_ERROR = 'GET_ERROR_RMDIDS_ERROR'
export const GET_ERROR_RMDLIST_SUCCESS = 'GET_ERROR_RMDLIST_SUCCESS'
export const GET_ERROR_RMDLIST_ERROR = 'GET_ERROR_RMDLIST_ERROR'
/*归纳本错题提交*/
export const POST_ERROR_RECOMMENDIDS_SUCCESS = 'POST_ERROR_RECOMMENDIDS_SUCCESS'
export const POST_ERROR_RECOMMENDIDS_ERROR = 'POST_ERROR_RECOMMENDIDS_ERROR'
