//Toast
export const GET_TOAST_MESSAGE = 'GET_TOAST_MESSAGE'
export const GET_TOAST_SHOW = 'GET_TOAST_SHOW'
//Loading
export const GET_LOADING = 'GET_LOADING'

/*获取习题列表*/
export const GET_COLLECT_EXAMPLELIST_SUCCESS = 'GET_COLLECT_EXAMPLELIST_SUCCESS'
export const GET_COLLECT_EXAMPLELIST_ERROR = 'GET_COLLECT_EXAMPLELIST_ERROR'
/*获取拍错题列表*/
export const GET_COLLECT_CAMERALIST_SUCCESS = 'GET_COLLECT_CAMERALIST_SUCCESS'
export const GET_COLLECT_CAMERALIST_ERROR = 'GET_COLLECT_CAMERALIST_ERROR'
