//Toast
export const GET_TOAST_MESSAGE = 'GET_TOAST_MESSAGE'
export const GET_TOAST_SHOW = 'GET_TOAST_SHOW'
//Loading
export const GET_LOADING = 'GET_LOADING'
/*取消收藏*/
export const COLLECT_CANCEL_SUCCESS = 'COLLECT_CANCEL_SUCCESS'
export const COLLECT_CANCEL_ERROR = 'COLLECT_CANCEL_ERROR'
/*添加收藏*/
export const COLLECT_ADD_SUCCESS = 'COLLECT_ADD_SUCCESS'
export const COLLECT_ADD_ERROR = 'COLLECT_ADD_ERROR'
/*评注*/
export const COMMENT_SUCCESS = 'COMMENT_SUCCESS'
export const COMMENT_ERROR = 'COMMENT_ERROR'
/*纠错*/
export const CORRECT_SUCCESS = 'CORRECT_SUCCESS'
export const CORRECT_ERROR = 'CORRECT_ERROR'
