/**  获取收藏列表ID*/
export const GET_COLLECT_CAMERALEIDS = 'GET_COLLECT_CAMERALEIDS'
/** 获取拍错题列表ID*/
export const GET_COLLECT_EXAMPLEIDS = 'GET_COLLECT_EXAMPLEIDS'
/** 获取习题详情*/
export const GET_COLLECT_EXAMPLEDETAIL = 'GET_COLLECT_EXAMPLEDETAIL'
/** 获取拍错题详情*/
export const GET_COLLECT_CAMERADETAIL = 'GET_COLLECT_CAMERADETAIL'
/** 获取收藏数据*/
export const GET_COLLECT_CAMERALELIST = 'GET_COLLECT_CAMERALELIST'
/** 获取拍错题数据*/
export const GET_COLLECT_EXAMPLELIST = 'GET_COLLECT_EXAMPLELIST'
/** 收藏本课程切换*/
export const COLLECT_SUBJECT_CHANGE = 'COLLECT_SUBJECT_CHANGE'
/** 收藏本滚动*/
export const COLLECT_INDEX_SCOLL = 'COLLECT_INDEX_SCOLL'
/** 收藏本数据清空*/
export const COLLECT_RELOAD = 'COLLECT_RELOAD'
