/*获取收藏列表ID*/
export const GET_COLLECT_CAMERALEIDS_SUCCESS = 'GET_REGISTER_MESSAGE_SUCCESS'
export const GET_COLLECT_CAMERALEIDS_ERROR = 'GET_REGISTER_MESSAGE_ERROR'
/*获取拍错题列表ID*/
export const GET_COLLECT_EXAMPLEIDS_SUCCESS = 'GET_FORGET_MESSAGE_SUCCESS'
export const GET_COLLECT_EXAMPLEIDS_ERROR = 'GET_FORGET_MESSAGE_ERROR'