/**  获取收藏列表ID*/
export const GET_COLLECT_CAMERALEIDS = 'GET_REGISTER_MESSAGE'
/** 获取拍错题列表ID*/
export const GET_COLLECT_EXAMPLEIDS = 'GET_FORGET_MESSAGE'
/** 获取收藏数据*/
export const GET_COLLECT_CAMERALELIST = 'GET_COLLECT_CAMERALELIST'
/** 获取拍错题数据*/
export const GET_COLLECT_EXAMPLELIST = 'GET_COLLECT_EXAMPLELIST'
/** 收藏本课程切换*/
export const COLLECT_SUBJECT_CHANGE = 'COLLECT_SUBJECT_CHANGE'
/** 收藏本数据清空*/
export const COLLECT_RELOAD = 'COLLECT_RELOAD'
