/*获取消息状态*/
export const GET_INTERACT_HOME_SUCCESS = 'GET_INTERACT_HOME_SUCCESS'
export const GET_INTERACT_HOME_ERROR = 'GET_INTERACT_HOME_ERROR'
/*获取系统消息*/
export const GET_INTERACT_SYSTEM_SUCCESS = 'GET_INTERACT_SYSTEM_SUCCESS'
export const GET_INTERACT_SYSTEM_ERROR = 'GET_INTERACT_SYSTEM_ERROR'
/*获取纠错消息*/
export const GET_INTERACT_CORRECT_SUCCESS = 'GET_INTERACT_CORRECT_SUCCESS'
export const GET_INTERACT_CORRECT_ERROR = 'GET_INTERACT_CORRECT_ERROR'
/*获取班级消息*/
export const GET_INTERACT_CLASS_SUCCESS = 'GET_INTERACT_CLASS_SUCCESS'
export const GET_INTERACT_CLASS_ERROR = 'GET_INTERACT_CLASS_ERROR'

