/** 记错题列表 */
export const STATISTICS_REMEMBER = 'STATISTICS_REMEMBER'
/** 记错题筛选 */
export const STATISTICS_REMEMBER_OPTIONS = 'STATISTICS_REMEMBER_OPTIONS'
/** 记错题组卷列表 */
export const STATISTICS_REMEMBER_ASSEMBLE = 'STATISTICS_REMEMBER_ASSEMBLE'
/** 记错题组卷勾选 */
export const STATISTICS_REMEMBER_ASSEMBLE_UPDATE = 'STATISTICS_REMEMBER_ASSEMBLE_UPDATE'
/** 记错题清空 */
export const STATISTICS_REMEMBER_RESET = 'STATISTICS_REMEMBER_RESET'
/** 拍错题列表 */
export const STATISTICS_CAMERA = 'STATISTICS_CAMERA'
/** 拍错题组卷列表 */
export const STATISTICS_CAMERA_ASSEMBLE = 'STATISTICS_CAMERA_ASSEMBLE'
/** 拍错题组卷勾选 */
export const STATISTICS_CAMERA_ASSEMBLE_UPDATE = 'STATISTICS_CAMERA_ASSEMBLE_UPDATE'
/** 拍错题清空 */
export const STATISTICS_CAMERA_RESET = 'STATISTICS_REMEMBER_RESET'
/** 精选题列表 */
export const STATISTICS_GOOD = 'STATISTICS_GOOD'
/** 精选题筛选 */
export const STATISTICS_GOOD_OPTIONS = 'STATISTICS_GOOD_OPTIONS'
/** 精选题详情 */
export const STATISTICS_GOOD_DETAIL = 'STATISTICS_GOOD_DETAIL'
/** 精选题清空 */
export const STATISTICS_GOOD_RESET = 'TATISTICS_GOOD_RESET'
/** 精选相似题列表 */
export const STATISTICS_GOOD_SIMILARITY_LIST = 'STATISTICS_GOOD_SIMILARITY_LIST'
/** 精选相似题清空 */
export const STATISTICS_GOOD_SIMILARITY_RESET = 'STATISTICS_GOOD_SIMILARITY_RESET'
/** 精选相似题组卷勾选 */
export const STATISTICS_GOOD_SIMILARITY_ASSEMBLE = 'STATISTICS_GOOD_SIMILARITY_ASSEMBLE'
/** 精选题组卷 */
export const STATISTICS_GOOD_ASSEMBLE = 'STATISTICS_GOOD_ASSEMBLE'
/** 精选题组卷勾选 */
export const STATISTICS_GOOD_ASSEMBLE_UPDATE = 'STATISTICS_GOOD_ASSEMBLE_UPDATE'
/** 精选题移动 */
export const STATISTICS_GOOD_ASSEMBLE_ORDER = 'STATISTICS_GOOD_ASSEMBLE_ORDER'
/** 列表下载 */
export const STATISTICS_DOWNLOAD = 'STATISTICS_DOWNLOAD'
/** 高度保存 */
export const STATISTICS_SCROLL = 'STATISTICS_SCROLL'
